In [3]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 835.9 KB

In [6]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [8]:
#How should we replace the null value?

In [9]:
#Through Mean or Median
#Generally medain > Mean
#Because meadian doesnt get affected by outliars 
#common mistake when we do is like find the median of entire column and replace it with null value , which is technacilly correct but not the ideal one.
#Ratings can vary a lot
#diff categories can have different rating which can force bias into our dataset

In [10]:
#We Will impute median into review rating within each categories

In [11]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [12]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [13]:
#we can see that the column names are in different cases and have spaces between them , which can cause multiple problems when analysing the dataset

In [14]:
#Snake_cases
#eg: customer_id

In [15]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [16]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [17]:
#create a column age_group


labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [18]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [19]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle-aged
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young Adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle-aged
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young Adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle-aged

In [20]:
purchases = df['frequency_of_purchases'].tolist()
print(purchases)

['Fortnightly', 'Fortnightly', 'Weekly', 'Weekly', 'Annually', 'Weekly', 'Quarterly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly', 'Fortnightly', 'Fortnightly', 'Weekly', 'Weekly', 'Monthly', 'Bi-Weekly', 'Quarterly', 'Weekly', 'Bi-Weekly', 'Every 3 Months', 'Quarterly', 'Annually', 'Weekly', 'Weekly', 'Annually', 'Annually', 'Every 3 Months', 'Every 3 Months', 'Weekly', 'Monthly', 'Monthly', 'Annually', 'Quarterly', 'Quarterly', 'Bi-Weekly', 'Fortnightly', 'Weekly', 'Every 3 Months', 'Monthly', 'Quarterly', 'Annually', 'Annually', 'Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Weekly', 'Monthly', 'Bi-Weekly', 'Bi-Weekly', 'Quarterly', 'Weekly', 'Weekly', 'Bi-Weekly', 'Annually', 'Weekly', 'Fortnightly', 'Monthly', 'Weekly', 'Weekly', 'Every 3 Months', 'Fortnightly', 'Weekly', 'Fortnightly', 'Every 3 Months', 'Every 3 Months', 'Monthly', 'Every 3 Months', 'Weekly', 'Every 3 Months', 'Annually', 'Every 3 Months', 'Bi-Weekly', 'Monthly', 'Annually', 'Monthly', 'Fortnightly', 'Fortnightly', 'Every 3 Months', 'Every 3 Months', 'Every 3 Months', 'Every 3 Months', 'Weekly', 'Every 3 Months', 'Bi-Weekly', 'Bi-Weekly', 'Fortnightly', 'Monthly', 'Quarterly', 'Monthly', 'Every 3 Months', 'Every 3 Months', 'Weekly', 'Weekly', 'Monthly', 'Every 3 Months', 'Annually', 'Annually', 'Quarterly', 'Fortnightly', 'Bi-Weekly', 'Quarterly', 'Bi-Weekly', 'Monthly', 'Annually', 'Monthly', 'Fortnightly', 'Bi-Weekly', 'Fortnightly', 'Fortnightly', 'Annually', 'Bi-Weekly', 'Quarterly', 'Weekly', 'Every 3 Months', 'Annually', 'Fortnightly', 'Bi-Weekly', 'Annually', 'Annually', 'Fortnightly', 'Fortnightly', 'Weekly', 'Annually', 'Every 3 Months', 'Every 3 Months', 'Weekly', 'Fortnightly', 'Bi-Weekly', 'Fortnightly', 'Weekly', 'Weekly', 'Annually', 'Monthly', 'Quarterly', 'Quarterly', 'Weekly', 'Weekly', 'Annually', 'Weekly', 'Weekly', 'Fortnightly', 'Quarterly', 'Monthly', 'Quarterly', 'Fortnightly', 'Fortnightly', 'Annually', 'Monthly', 'Every 3 Months', 'Annually', 'Annually', 'Annually', 'Quarterly', 'Quarterly', 'Annually', 'Fortnightly', 'Monthly', 'Every 3 Months', 'Monthly', 'Fortnightly', 'Bi-Weekly', 'Weekly', 'Fortnightly', 'Monthly', 'Monthly', 'Every 3 Months', 'Fortnightly', 'Every 3 Months', 'Bi-Weekly', 'Weekly', 'Bi-Weekly', 'Annually', 'Annually', 'Annually', 'Quarterly', 'Monthly', 'Quarterly', 'Fortnightly', 'Fortnightly', 'Weekly', 'Annually', 'Weekly', 'Fortnightly', 'Fortnightly', 'Annually', 'Bi-Weekly', 'Bi-Weekly', 'Weekly', 'Quarterly', 'Every 3 Months', 'Bi-Weekly', 'Annually', 'Quarterly', 'Monthly', 'Fortnightly', 'Monthly', 'Fortnightly', 'Weekly', 'Monthly', 'Annually', 'Annually', 'Weekly', 'Bi-Weekly', 'Weekly', 'Fortnightly', 'Bi-Weekly', 'Monthly', 'Every 3 Months', 'Fortnightly', 'Fortnightly', 'Annually', 'Every 3 Months', 'Every 3 Months', 'Bi-Weekly', 'Weekly', 'Annually', 'Quarterly', 'Fortnightly', 'Fortnightly', 'Quarterly', 'Fortnightly', 'Annually', 'Every 3 Months', 'Annually', 'Monthly', 'Fortnightly', 'Annually', 'Every 3 Months', 'Annually', 'Every 3 Months', 'Bi-Weekly', 'Every 3 Months', 'Weekly', 'Quarterly', 'Fortnightly', 'Fortnightly', 'Annually', 'Bi-Weekly', 'Fortnightly', 'Bi-Weekly', 'Every 3 Months', 'Monthly', 'Weekly', 'Fortnightly', 'Bi-Weekly', 'Weekly', 'Weekly', 'Annually', 'Weekly', 'Annually', 'Fortnightly', 'Bi-Weekly', 'Bi-Weekly', 'Annually', 'Every 3 Months', 'Quarterly', 'Quarterly', 'Annually', 'Every 3 Months', 'Annually', 'Annually', 'Monthly', 'Annually', 'Bi-Weekly', 'Weekly', 'Annually', 'Monthly', 'Bi-Weekly', 'Annually', 'Fortnightly', 'Bi-Weekly', 'Quarterly', 'Bi-Weekly', 'Weekly', 'Fortnightly', 'Bi-Weekly', 'Annually', 'Monthly', 'Bi-Weekly', 'Bi-Weekly', 'Monthly', 'Annually', 'Quarterly', 'Bi-Weekly', 'Annually', 'Fortnightly', 'Bi-Weekly', 'Monthly', 'Weekly', 'Monthly', 'Quarterly', 'Annually', 'Every 3 Months', 'Quarterly', 'Weekly', 'Bi-Weekly', 'Every 3 Months', 'Fortnightly', 'Weekly', 'Every 3 Months', 'Every 3 Months', 'Weekly', 'Bi-Weekly', 'Annually', 'Annually', 'Every 3 Months', 'Bi-Weekly', 'Fortnightly', 'Fortnightly', 'Monthly', 'Annually', 'Every 3 Months', 'Every 3 Months', 'Annually', 'Monthly', 'Every 3 Months', 'Annually', 'Every 3 Months', 'Quarterly', 'Quarterly', 'Monthly', 'Bi-Weekly', 'Quarterly', 'Annually', 'Weekly', 'Weekly', 'Weekly', 'Monthly', 'Bi-Weekly', 'Quarterly', 'Monthly', 'Bi-Weekly', 'Annually', 'Every 3 Months', 'Annually', 'Annually', 'Weekly', 'Every 3 Months', 'Every 3 Months', 'Bi-Weekly', 'Every 3 Months', 'Monthly', 'Monthly', 'Annually', 'Weekly', 'Fortnightly', 'Fortnightly', 'Bi-Weekly', 'Fortnightly', 'Bi-Weekly', 'Every 3 Months', 'Monthly', 'Weekly', 'Every 3 Months', 'Weekly', 'Bi-Weekly', 'Every 3 Months', 'Every 3 Months', 'Fortnightly', 'Annually', 'Fortnightly', 'Fortnightly', 'Every 3 Months', 'Quarterly', 'Fortnightly', 'Monthly', 'Monthly', 'Quarterly', 'Weekly', 'Monthly', 'Weekly', 'Bi-Weekly', 'Monthly', 'Quarterly', 'Bi-Weekly', 'Every 3 Months', 'Monthly', 'Bi-Weekly', 'Weekly', 'Every 3 Months', 'Quarterly', 'Quarterly', 'Annually', 'Bi-Weekly', 'Quarterly', 'Fortnightly', 'Quarterly', 'Monthly', 'Annually', 'Fortnightly', 'Annually', 'Fortnightly', 'Bi-Weekly', 'Annually', 'Annually', 'Annually', 'Every 3 Months', 'Monthly', 'Fortnightly', 'Quarterly', 'Monthly', 'Annually', 'Monthly', 'Annually', 'Monthly', 'Bi-Weekly', 'Fortnightly', 'Monthly', 'Quarterly', 'Annually', 'Weekly', 'Monthly', 'Weekly', 'Monthly', 'Fortnightly', 'Quarterly', 'Bi-Weekly', 'Every 3 Months', 'Bi-Weekly', 'Bi-Weekly', 'Annually', 'Bi-Weekly', 'Fortnightly', 'Quarterly', 'Quarterly', 'Quarterly', 'Fortnightly', 'Fortnightly', 'Annually', 'Fortnightly', 'Weekly', 'Fortnightly', 'Every 3 Months', 'Monthly', 'Weekly', 'Annually', 'Fortnightly', 'Monthly', 'Fortnightly', 'Annually', 'Quarterly', 'Annually', 'Annually', 'Annually', 'Monthly', 'Every 3 Months', 'Fortnightly', 'Monthly', 'Monthly', 'Fortnightly', 'Fortnightly', 'Weekly', 'Bi-Weekly', 'Fortnightly', 'Quarterly', 'Every 3 Months', 'Monthly', 'Fortnightly', 'Weekly', 'Weekly', 'Every 3 Months', 'Weekly', 'Monthly', 'Quarterly', 'Weekly', 'Every 3 Months', 'Quarterly', 'Bi-Weekly', 'Every 3 Months', 'Quarterly', 'Quarterly', 'Every 3 Months', 'Quarterly', 'Annually', 'Fortnightly', 'Weekly', 'Annually', 'Monthly', 'Bi-Weekly', 'Fortnightly', 'Annually', 'Weekly', 'Quarterly', 'Fortnightly', 'Every 3 Months', 'Quarterly', 'Weekly', 'Annually', 'Monthly', 'Bi-Weekly', 'Weekly', 'Bi-Weekly', 'Weekly', 'Fortnightly', 'Fortnightly', 'Weekly', 'Monthly', 'Monthly', 'Every 3 Months', 'Annually', 'Fortnightly', 'Quarterly', 'Annually', 'Bi-Weekly', 'Annually', 'Fortnightly', 'Quarterly', 'Weekly', 'Annually', 'Annually', 'Monthly', 'Annually', 'Quarterly', 'Monthly', 'Bi-Weekly', 'Every 3 Months', 'Every 3 Months', 'Quarterly', 'Quarterly', 'Annually', 'Quarterly', 'Quarterly', 'Annually', 'Monthly', 'Monthly', 'Every 3 Months', 'Annually', 'Monthly', 'Bi-Weekly', 'Weekly', 'Every 3 Months', 'Weekly', 'Quarterly', 'Weekly', 'Every 3 Months', 'Annually', 'Weekly', 'Weekly', 'Every 3 Months', 'Bi-Weekly', 'Bi-Weekly', 'Monthly', 'Every 3 Months', 'Annually', 'Bi-Weekly', 'Weekly', 'Every 3 Months', 'Bi-Weekly', 'Weekly', 'Bi-Weekly', 'Weekly', 'Quarterly', 'Weekly', 'Annually', 'Fortnightly', 'Weekly', 'Every 3 Months', 'Monthly', 'Annually', 'Fortnightly', 'Annually', 'Quarterly', 'Weekly', 'Weekly', 'Fortnightly', 'Fortnightly', 'Monthly', 'Every 3 Months', 'Annually', 'Weekly', 'Annually', 'Bi-Weekly', 'Bi-Weekly', 'Monthly', 'Every 3 Months', 'Annually', 'Fortnightly', 'Annually', 'Weekly', 'Every 3 Months', 'Quarterly', 'Monthly', 'Monthly', 'Every 3 Months', 'Annually', 'Every 3 Months', 'Quarterly', 'Annually', 'Fortnightly', 'Bi-Weekly', 'Every 3 Months', 'Every 3 Months', 'Monthly', 'Quarterly', 'Annually', 'Fortnightly', 'Every 3 Months', 'Every 3 Months', 'Monthly', 'Fortnightly', 'Every 3 Months', 'Every 3 Months', 'Every 3 Months', 'Weekly', 'Monthly', 'Monthly', 'Every 3 Months', 'Fortnightly', 'Every 3 Months', 'Monthly', 'Quarterly', 'Bi-Weekly', 'Bi-Weekly', 'Annually', 'Every 3 Months', 'Quarterly', 'Bi-Weekly', 'Every 3 Months', 'Every 3 Months', 'Weekly', 'Fortnightly', 'Bi-Weekly', 'Annually', 'Weekly', 'Annually', 'Monthly', 'Monthly', 'Annually', 'Annually', 'Fortnightly', 'Fortnightly', 'Quarterly', 'Weekly', 'Quarterly', 'Every 3 Months', 'Fortnightly', 'Monthly', 'Annually', 'Fortnightly', 'Every 3 Months', 'Bi-Weekly', 'Every 3 Months', 'Weekly', 'Bi-Weekly', 'Bi-Weekly', 'Fortnightly', 'Weekly', 'Every 3 Months', 'Annually', 'Fortnightly', 'Weekly', 'Fortnightly', 'Annually', 'Monthly', 'Quarterly', 'Quarterly', 'Weekly', 'Weekly', 'Quarterly', 'Quarterly', 'Bi-Weekly', 'Monthly', 'Bi-Weekly', 'Annually', 'Quarterly', 'Quarterly', 'Monthly', 'Bi-Weekly', 'Bi-Weekly', 'Weekly', 'Quarterly', 'Bi-Weekly', 'Annually', 'Annually', 'Bi-Weekly', 'Annually', 'Every 3 Months', 'Fortnightly', 'Annually', 'Every 3 Months', 'Bi-Weekly', 'Monthly', 'Monthly', 'Fortnightly', 'Fortnightly', 'Quarterly', 'Monthly', 'Every 3 Months', 'Weekly', 'Bi-Weekly', 'Every 3 Months', 'Every 3 Months', 'Every 3 Months', 'Every 3 Months', 'Monthly', 'Quarterly', 'Weekly', 'Weekly', 'Monthly', 'Every 3 Months', 'Weekly', 'Weekly', 'Annually', 'Quarterly', 'Weekly', 'Annually', 'Fortnightly', 'Monthly', 'Fortnightly', 'Bi-Weekly', 'Quarterly', 'Bi-Weekly', 'Fortnightly', 'Quarterly', 'Bi-Weekly', 'Every 3 Months', 'Annually', 'Bi-Weekly', 'Weekly', 'Every 3 Months', 'Bi-Weekly', 'Monthly', 'Every 3 Months', 'Fortnightly', 'Every 3 Months', 'Every 3 Months', 'Every 3 Months', 'Every 3 Months', 'Fortnightly', 'Fortnightly', 'Bi-Weekly', 'Bi-Weekly', 'Every 3 Months', 'Bi-Weekly', 'Every 3 Months', 'Annually', 'Quarterly', 'Bi-Weekly', 'Fortnightly', 'Every 3 Months', 'Quarterly', 'Weekly', 'Bi-Weekly', 'Monthly', 'Annually', 'Weekly', 'Quarterly', 'Quarterly', 'Annually', 'Monthly', 'Every 3 Months', 'Quarterly', 'Quarterly', 'Weekly', 'Fortnightly', 'Quarterly', 'Every 3 Months', 'Fortnightly', 'Annually', 'Weekly', 'Fortnightly', 'Monthly', 'Quarterly', 'Quarterly', 'Monthly', 'Annually', 'Weekly', 'Monthly', 'Annually', 'Fortnightly', 'Bi-Weekly', 'Bi-Weekly', 'Quarterly', 'Monthly', 'Every 3 Months', 'Weekly', 'Annually', 'Annually', 'Quarterly', 'Fortnightly', 'Weekly', 'Fortnightly', 'Every 3 Months', 'Fortnightly', 'Every 3 Months', 'Weekly', 'Quarterly', 'Bi-Weekly', 'Quarterly', 'Fortnightly', 'Weekly', 'Monthly', 'Fortnightly', 'Annually', 'Annually', 'Weekly', 'Every 3 Months', 'Annually', 'Every 3 Months', 'Fortnightly', 'Weekly', 'Every 3 Months', 'Quarterly', 'Monthly', 'Quarterly', 'Weekly', 'Every 3 Months', 'Bi-Weekly', 'Bi-Weekly', 'Quarterly', 'Weekly', 'Annually', 'Monthly', 'Bi-Weekly', 'Monthly', 'Fortnightly', 'Monthly', 'Quarterly', 'Monthly', 'Bi-Weekly', 'Annually', 'Quarterly', 'Quarterly', 'Monthly', 'Weekly', 'Fortnightly', 'Bi-Weekly', 'Fortnightly', 'Annually', 'Every 3 Months', 'Bi-Weekly', 'Annually', 'Weekly', 'Weekly', 'Bi-Weekly', 'Every 3 Months', 'Annually', 'Every 3 Months', 'Weekly', 'Fortnightly', 'Weekly', 'Weekly', 'Bi-Weekly', 'Monthly', 'Quarterly', 'Monthly', 'Bi-Weekly', 'Quarterly', 'Monthly', 'Monthly', 'Every 3 Months', 'Monthly', 'Monthly', 'Quarterly', 'Fortnightly', 'Every 3 Months', 'Weekly', 'Monthly', 'Monthly', 'Every 3 Months', 'Fortnightly', 'Fortnightly', 'Annually', 'Annually', 'Bi-Weekly', 'Fortnightly', 'Every 3 Months', 'Weekly', 'Bi-Weekly', 'Quarterly', 'Quarterly', 'Quarterly', 'Every 3 Months', 'Every 3 Months', 'Weekly', 'Every 3 Months', 'Weekly', 'Quarterly', 'Monthly', 'Annually', 'Every 3 Months', 'Monthly', 'Weekly', 'Every 3 Months', 'Monthly', 'Fortnightly', 'Annually', 'Weekly', 'Monthly', 'Every 3 Months', 'Monthly', 'Monthly', 'Quarterly', 'Quarterly', 'Fortnightly', 'Weekly', 'Every 3 Months', 'Annually', 'Quarterly', 'Monthly', 'Monthly', 'Quarterly', 'Every 3 Months', 'Annually', 'Bi-Weekly', 'Bi-Weekly', 'Every 3 Months', 'Weekly', 'Monthly', 'Quarterly', 'Monthly', 'Every 3 Months', 'Every 3 Months', 'Fortnightly', 'Monthly', 'Quarterly', 'Fortnightly', 'Bi-Weekly', 'Weekly', 'Weekly', 'Monthly', 'Weekly', 'Quarterly', 'Monthly', 'Bi-Weekly', 'Bi-Weekly', 'Every 3 Months', 'Fortnightly', 'Bi-Weekly', 'Fortnightly', 'Bi-Weekly', 'Monthly', 'Monthly', 'Fortnightly', 'Weekly', 'Quarterly', 'Fortnightly', 'Monthly', 'Every 3 Months', 'Every 3 Months', 'Bi-Weekly', 'Fortnightly', 'Bi-Weekly', 'Every 3 Months', 'Quarterly', 'Every 3 Months', 'Every 3 Months', 'Monthly', 'Quarterly', 'Monthly', 'Monthly', 'Quarterly', 'Every 3 Months', 'Monthly', 'Quarterly', 'Quarterly', 'Bi-Weekly', 'Fortnightly', 'Quarterly', 'Quarterly', 'Fortnightly', 'Weekly', 'Bi-Weekly', 'Annually', 'Annually', 'Weekly', 'Quarterly', 'Monthly', 'Monthly', 'Weekly', 'Weekly', 'Quarterly', 'Monthly', 'Weekly', 'Every 3 Months', 'Bi-Weekly', 'Weekly', 'Monthly', 'Every 3 Months', 'Quarterly', 'Monthly', 'Bi-Weekly', 'Bi-Weekly', 'Annually', 'Monthly', 'Weekly', 'Fortnightly', 'Monthly', 'Weekly', 'Bi-Weekly', 'Weekly', 'Weekly', 'Monthly', 'Weekly', 'Quarterly', 'Fortnightly', 'Bi-Weekly', 'Monthly', 'Bi-Weekly', 'Fortnightly', 'Bi-Weekly', 'Bi-Weekly', 'Annually', 'Bi-Weekly', 'Quarterly', 'Annually', 'Annually', 'Annually', 'Fortnightly', 'Fortnightly', 'Annually', 'Bi-Weekly', 'Fortnightly', 'Weekly', 'Every 3 Months', 'Annually', 'Weekly', 'Bi-Weekly', 'Annually', 'Weekly', 'Annually', 'Every 3 Months', 'Quarterly', 'Annually', 'Bi-Weekly', 'Monthly', 'Fortnightly', 'Bi-Weekly', 'Quarterly', 'Quarterly', 'Quarterly', 'Quarterly', 'Weekly', 'Annually', 'Monthly', 'Quarterly', 'Weekly', 'Monthly', 'Fortnightly', 'Fortnightly', 'Weekly', 'Fortnightly', 'Every 3 Months', 'Bi-Weekly', 'Annually', 'Fortnightly', 'Fortnightly', 'Quarterly', 'Monthly', 'Annually', 'Fortnightly', 'Bi-Weekly', 'Quarterly', 'Annually', 'Fortnightly', 'Weekly', 'Every 3 Months', 'Monthly', 'Every 3 Months', 'Every 3 Months', 'Every 3 Months', 'Monthly', 'Every 3 Months', 'Every 3 Months', 'Bi-Weekly', 'Quarterly', 'Weekly', 'Every 3 Months', 'Weekly', 'Monthly', 'Fortnightly', 'Monthly', 'Fortnightly', 'Bi-Weekly', 'Bi-Weekly', 'Quarterly', 'Fortnightly', 'Monthly', 'Every 3 Months', 'Annually', 'Quarterly', 'Weekly', 'Quarterly', 'Fortnightly', 'Bi-Weekly', 'Monthly', 'Weekly', 'Bi-Weekly', 'Fortnightly', 'Fortnightly', 'Quarterly', 'Every 3 Months', 'Quarterly', 'Quarterly', 'Annually', 'Weekly', 'Weekly', 'Fortnightly', 'Weekly', 'Fortnightly', 'Fortnightly', 'Bi-Weekly', 'Quarterly', 'Every 3 Months', 'Fortnightly', 'Weekly', 'Fortnightly', 'Weekly', 'Bi-Weekly', 'Bi-Weekly', 'Quarterly', 'Bi-Weekly', 'Every 3 Months', 'Weekly', 'Fortnightly', 'Monthly', 'Every 3 Months', 'Weekly', 'Monthly', 'Quarterly', 'Annually', 'Monthly', 'Quarterly', 'Weekly', 'Fortnightly', 'Monthly', 'Monthly', 'Fortnightly', 'Bi-Weekly', 'Monthly', 'Fortnightly', 'Weekly', 'Every 3 Months', 'Quarterly', 'Monthly', 'Every 3 Months', 'Fortnightly', 'Bi-Weekly', 'Every 3 Months', 'Fortnightly', 'Bi-Weekly', 'Quarterly', 'Fortnightly', 'Every 3 Months', 'Every 3 Months', 'Annually', 'Fortnightly', 'Annually', 'Bi-Weekly', 'Weekly', 'Every 3 Months', 'Quarterly', 'Bi-Weekly', 'Quarterly', 'Every 3 Months', 'Quarterly', 'Annually', 'Every 3 Months', 'Bi-Weekly', 'Monthly', 'Weekly', 'Monthly', 'Quarterly', 'Every 3 Months', 'Fortnightly', 'Quarterly', 'Fortnightly', 'Annually', 'Bi-Weekly', 'Annually', 'Bi-Weekly', 'Bi-Weekly', 'Bi-Weekly', 'Quarterly', 'Quarterly', 'Monthly', 'Annually', 'Annually', 'Monthly', 'Quarterly', 'Quarterly', 'Weekly', 'Annually', 'Monthly', 'Annually', 'Every 3 Months', 'Weekly', 'Annually', 'Weekly', 'Quarterly', 'Quarterly', 'Fortnightly', 'Fortnightly', 'Monthly', 'Bi-Weekly', 'Annually', 'Annually', 'Weekly', 'Weekly', 'Fortnightly', 'Every 3 Months', 'Annually', 'Every 3 Months', 'Fortnightly', 'Every 3 Months', 'Every 3 Months', 'Annually', 'Monthly', 'Quarterly', 'Every 3 Months', 'Weekly', 'Every 3 Months', 'Every 3 Months', 'Every 3 Months', 'Every 3 Months', 'Every 3 Months', 'Every 3 Months', 'Bi-Weekly', 'Quarterly', 'Quarterly', 'Annually', 'Weekly', 'Weekly', 'Weekly', 'Bi-Weekly', 'Bi-Weekly', 'Annually', 'Annually', 'Monthly', 'Fortnightly', 'Every 3 Months', 'Every 3 Months', 'Bi-Weekly', 'Every 3 Months', 'Every 3 Months', 'Quarterly', 'Fortnightly', 'Every 3 Months', 'Annually', 'Weekly', 'Quarterly', 'Annually', 'Monthly', 'Weekly', 'Monthly', 'Bi-Weekly', 'Annually', 'Fortnightly', 'Monthly', 'Monthly', 'Quarterly', 'Annually', 'Bi-Weekly', 'Fortnightly', 'Fortnightly', 'Every 3 Months', 'Every 3 Months', 'Monthly', 'Quarterly', 'Fortnightly', 'Monthly', 'Bi-Weekly', 'Bi-Weekly', 'Weekly', 'Every 3 Months', 'Weekly', 'Bi-Weekly', 'Quarterly', 'Annually', 'Annually', 'Monthly', 'Every 3 Months', 'Quarterly', 'Monthly', 'Weekly', 'Quarterly', 'Fortnightly', 'Annually', 'Every 3 Months', 'Bi-Weekly', 'Monthly', 'Every 3 Months', 'Fortnightly', 'Fortnightly', 'Fortnightly', 'Monthly', 'Bi-Weekly', 'Weekly', 'Annually', 'Fortnightly', 'Annually', 'Annually', 'Every 3 Months', 'Weekly', 'Bi-Weekly', 'Annually', 'Fortnightly', 'Bi-Weekly', 'Every 3 Months', 'Weekly', 'Monthly', 'Annually', 'Every 3 Months', 'Every 3 Months', 'Annually', 'Annually', 'Every 3 Months', 'Quarterly', 'Every 3 Months', 'Annually', 'Monthly', 'Bi-Weekly', 'Annually', 'Quarterly', 'Bi-Weekly', 'Monthly', 'Bi-Weekly', 'Weekly', 'Annually', 'Every 3 Months', 'Quarterly', 'Every 3 Months', 'Fortnightly', 'Monthly', 'Monthly', 'Weekly', 'Weekly', 'Every 3 Months', 'Bi-Weekly', 'Bi-Weekly', 'Quarterly', 'Quarterly', 'Monthly', 'Weekly', 'Fortnightly', 'Bi-Weekly', 'Fortnightly', 'Every 3 Months', 'Every 3 Months', 'Quarterly', 'Monthly', 'Monthly', 'Annually', 'Weekly', 'Bi-Weekly', 'Monthly', 'Fortnightly', 'Bi-Weekly', 'Every 3 Months', 'Quarterly', 'Bi-Weekly', 'Every 3 Months', 'Quarterly', 'Bi-Weekly', 'Annually', 'Quarterly', 'Every 3 Months', 'Fortnightly', 'Annually', 'Monthly', 'Weekly', 'Quarterly', 'Every 3 Months', 'Fortnightly', 'Fortnightly', 'Quarterly', 'Weekly', 'Fortnightly', 'Every 3 Months', 'Monthly', 'Bi-Weekly', 'Quarterly', 'Quarterly', 'Annually', 'Annually', 'Monthly', 'Weekly', 'Bi-Weekly', 'Fortnightly', 'Quarterly', 'Quarterly', 'Monthly', 'Weekly', 'Bi-Weekly', 'Quarterly', 'Monthly', 'Quarterly', 'Fortnightly', 'Weekly', 'Annually', 'Every 3 Months', 'Fortnightly', 'Weekly', 'Bi-Weekly', 'Monthly', 'Annually', 'Weekly', 'Annually', 'Every 3 Months', 'Weekly', 'Monthly', 'Bi-Weekly', 'Weekly', 'Monthly', 'Monthly', 'Annually', 'Weekly', 'Fortnightly', 'Annually', 'Quarterly', 'Annually', 'Quarterly', 'Bi-Weekly', 'Every 3 Months', 'Quarterly', 'Fortnightly', 'Every 3 Months', 'Quarterly', 'Every 3 Months', 'Fortnightly', 'Bi-Weekly', 'Every 3 Months', 'Every 3 Months', 'Annually', 'Every 3 Months', 'Annually', 'Quarterly', 'Every 3 Months', 'Fortnightly', 'Quarterly', 'Quarterly', 'Weekly', 'Bi-Weekly', 'Weekly', 'Fortnightly', 'Annually', 'Monthly', 'Fortnightly', 'Monthly', 'Every 3 Months', 'Annually', 'Monthly', 'Quarterly', 'Annually', 'Quarterly', 'Monthly', 'Every 3 Months', 'Every 3 Months', 'Quarterly', 'Quarterly', 'Quarterly', 'Fortnightly', 'Annually', 'Every 3 Months', 'Every 3 Months', 'Fortnightly', 'Weekly', 'Fortnightly', 'Bi-Weekly', 'Quarterly', 'Quarterly', 'Monthly', 'Quarterly', 'Bi-Weekly', 'Annually', 'Fortnightly', 'Fortnightly', 'Every 3 Months', 'Every 3 Months', 'Every 3 Months', 'Weekly', 'Every 3 Months', 'Monthly', 'Monthly', 'Monthly', 'Every 3 Months', 'Bi-Weekly', 'Weekly', 'Quarterly', 'Quarterly', 'Weekly', 'Bi-Weekly', 'Every 3 Months', 'Fortnightly', 'Every 3 Months', 'Annually', 'Weekly', 'Quarterly', 'Bi-Weekly', 'Quarterly', 'Quarterly', 'Quarterly', 'Fortnightly', 'Weekly', 'Bi-Weekly', 'Every 3 Months', 'Fortnightly', 'Every 3 Months', 'Monthly', 'Every 3 Months', 'Fortnightly', 'Quarterly', 'Monthly', 'Monthly', 'Quarterly', 'Annually', 'Every 3 Months', 'Annually', 'Annually', 'Wee

In [21]:
#create purchase_frequency_days

frequency_mapping = {
    'Fortnightly' : 14,
    'Weekly' : 7,
    'Monthly' : 30,
    'Quarterly' : 90,
    'Bi-Weekly' : 14,
    'Annually' : 365,
    'Every 3 Months' : 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [22]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [23]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [24]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [25]:
#We can see that both of the aboce columns contains exactly the same numbers

In [26]:
df = df.drop('promo_code_used', axis=1)

In [27]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [28]:
df.head(10)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14,Venmo,Weekly,Middle-aged,7
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Quarterly,Senior,90
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19,Credit Card,Weekly,Young Adult,7
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Annually,Young Adult,365
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4,Cash,Quarterly,Middle-aged,90

In [29]:
#install psycopg2 and sqlalchemy

In [31]:
!pip install psycopg2-binary sqlalchemy
#for MSQL we can change psycopg2-binary to pyodbc
#for MYSQL - pymysql
#if pip install does not work add ! as !pip

Requirement already satisfied: psycopg2-binary in .\anaconda3\Lib\site-packages (2.9.13)
Requirement already satisfied: sqlalchemy in .\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in .\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)

In [32]:
from sqlalchemy import create_engine
#connection with PostgresSQL


username = 'postgres'
password = 'mayank123'
host = 'localhost'
port = '5432'
database = 'customer_behaviour'

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#load the dataframe

table_name = 'customer'
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into the table '{table_name}' in database '{database}'.")

Data successfully loaded into the table 'customer' in database 'customer_behaviour'.